# Database Schema Documentation
# Database: u105991616_pensantasite (movilbasite)
# DBMS: MariaDB 11.8.3
# Purpose: Emoji search and management system

database:
  name: u105991616_pensantasite
  profile: movilbasite
  host: pensanta.com.ar
  port: 3306
  type: mysql
  version: 11.8.3-MariaDB-log

  statistics:
    total_tables: 3
    total_views: 1
    total_size_mb: 0.46
    emojis_record_count: 1876

tables:
  emojis:
    description: Main emoji table storing all emoji data
    record_count: 1876
    primary_key: id
    columns:
      - name: id
        type: int(11)
        nullable: false
        key: PRIMARY
        extra: auto_increment
        description: Unique identifier for each emoji

      - name: unicode
        type: varchar(20)
        nullable: false
        key: UNIQUE
        description: Unicode representation of the emoji

      - name: emojiChar
        type: varchar(10)
        nullable: false
        description: The actual emoji character

      - name: category
        type: varchar(50)
        nullable: false
        key: INDEX (idxCategory)
        description: Emoji category classification

      - name: name
        type: varchar(100)
        nullable: false
        key: INDEX (idxName)
        description: Name or description of the emoji

      - name: dontShow
        type: tinyint(1)
        nullable: true
        default: 0
        key: INDEX (idxDontShow)
        description: Flag to hide emoji from display (0=show, 1=hide)

      - name: createdAt
        type: timestamp
        nullable: true
        default: current_timestamp()
        description: Timestamp of record creation

    indexes:
      - name: PRIMARY
        columns: [id]
        unique: true
      - name: unicode
        columns: [unicode]
        unique: true
      - name: idxCategory
        columns: [category]
        unique: false
      - name: idxName
        columns: [name]
        unique: false
      - name: idxDontShow
        columns: [dontShow]
        unique: false

  keywords:
    description: Search keywords associated with emojis
    record_count: 0
    primary_key: id
    columns:
      - name: id
        type: int(11)
        nullable: false
        key: PRIMARY
        extra: auto_increment
        description: Unique identifier for each keyword

      - name: emojiId
        type: int(11)
        nullable: false
        key: FOREIGN KEY
        description: References emojis.id

      - name: keyword
        type: varchar(100)
        nullable: false
        key: INDEX (idxKeyword)
        description: Search keyword for emoji discovery

      - name: createdAt
        type: timestamp
        nullable: true
        default: current_timestamp()
        description: Timestamp of record creation

    indexes:
      - name: PRIMARY
        columns: [id]
        unique: true
      - name: idxKeyword
        columns: [keyword]
        unique: false
      - name: uniqueEmojiKeyword
        columns: [emojiId, keyword]
        unique: true
        description: Prevents duplicate keywords for same emoji

    foreign_keys:
      - name: keywords_ibfk_1
        column: emojiId
        references:
          table: emojis
          column: id
        on_delete: RESTRICT
        on_update: RESTRICT

  rateLimit:
    description: Rate limiting tracking by IP address
    record_count: 0
    primary_key: ip
    columns:
      - name: ip
        type: varchar(45)
        nullable: false
        key: PRIMARY
        description: IP address (supports IPv4 and IPv6)

      - name: searchCount
        type: int(11)
        nullable: true
        default: 0
        description: Number of searches within the current window

      - name: windowStart
        type: timestamp
        nullable: true
        default: current_timestamp()
        extra: on update current_timestamp()
        description: Start of the current rate limit window

    indexes:
      - name: PRIMARY
        columns: [ip]
        unique: true
      - name: idxWindow
        columns: [windowStart]
        unique: false

views:
  vEmojis:
    description: Filtered view of visible emojis (where dontShow = 0)
    source_table: emojis
    definition: |
      SELECT
        id,
        unicode,
        emojiChar,
        category,
        name,
        dontShow,
        createdAt
      FROM emojis
      WHERE dontShow = 0
    record_count: 1876

relationships:
  - from: keywords.emojiId
    to: emojis.id
    type: many-to-one
    constraint: keywords_ibfk_1
    description: Each keyword belongs to one emoji; each emoji can have multiple keywords

data_flow:
  - description: Users search for emojis by keywords
    steps:
      - Check rateLimit table for IP address
      - Query keywords table for matching search terms
      - Join with emojis table to retrieve emoji data
      - Filter using vEmojis view to exclude hidden emojis
      - Return results to user
      - Update rateLimit counters

notes:
  - Current state: 1876 emojis loaded, but no keywords assigned yet
  - All emojis currently visible (dontShow = 0 for all records)
  - No rate limiting data yet (rateLimit table empty)
  - Unique constraint on keywords prevents duplicate keyword-emoji pairs
  - Unicode field is unique to prevent duplicate emoji entries
